# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8
      - image: circleci/python:2.7.13


    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install test tools
          command: npm install jest-junit jest-cli

      # run tests!
      - run:
          name: Tests
          command: npm test --env=jsdom

      # run coverage!
      - run:
          name: Coverage
          command: mkdir /tmp/reports && JEST_JUNIT_OUTPUT="/tmp/reports/test-report.xml" npm run test -- --coverage --testResultsProcessor="jest-junit"

      - store_test_results:
          path: /tmp/reports

      - deploy:
          name: Deploy
          command: echo "won't deploy"

